// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMe9mci8tk9r24xWKtZ9tKokuLIyTagiA',
    appId: '1:389037316606:web:f3c79944836320524388af',
    messagingSenderId: '389037316606',
    projectId: 'playground-6d03a',
    authDomain: 'playground-6d03a.firebaseapp.com',
    databaseURL:
        'https://playground-6d03a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'playground-6d03a.appspot.com',
    measurementId: 'G-6QJQCP4YZ1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdwOe7iUeVqlWB_wnQHZoC4fqhA_PhC8E',
    appId: '1:389037316606:android:024d6f61cf558ebc4388af',
    messagingSenderId: '389037316606',
    projectId: 'playground-6d03a',
    databaseURL:
        'https://playground-6d03a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'playground-6d03a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPmsTLibuoLS1nr9mgmgXT2Ha8l0fI6pY',
    appId: '1:389037316606:ios:7c265b818b360fb94388af',
    messagingSenderId: '389037316606',
    projectId: 'playground-6d03a',
    databaseURL:
        'https://playground-6d03a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'playground-6d03a.appspot.com',
    iosClientId:
        '389037316606-hjrqgp4b4hq7c2mdoflgln17j5gl5dve.apps.googleusercontent.com',
    iosBundleId: 'io.flutter.app',
  );
}
